### ISSUE TITLE
Need to contact you!

### ISSUE THREAD

**Issue by yasharpm** [blackandred/test#1]
Hello @blackandred , I was not able to find another way contact you. I am looking to "connect" anarchist workers so that we can form teams and have more impact together. My email is yasharpm [aat] gmail. Please reply even if you not interested so that I can scratch you from the list in my mind!
Bests,
Yashar

**Comment by blackandred** [comment]
Hi, thanks for contacting. I will send you an e-mail soon :)

**Comment by blackandred** [comment]
Sent :)
